.gitignore, NewWindowChur/images.qrc, NewWindowChur/mainwindow.cpp
=> Adding Image

NewWindowChur/catalogue.cpp
after switching our catalogue, the search function was having issues.
=> fixed search function

NewWindowChur/createfiles.cpp, NewWindowChur/createfiles.h
Create member functions takes parameters: first name, last name, username, password, email, and phone number
It will then generate a random id ("Mem0000") in the function. It will also check the members file to see if the id exists already. If it does, it will keep generating an Id until it's unique.
=> Wrote CreateMember function

NewWindowChur/NewWindowChur.pro, NewWindowChur/NewWindowChur.pro.user, NewWindowChur/admin.cpp, NewWindowChur/admin.h, NewWindowChur/admin.ui, NewWindowChur/admindue.cpp, NewWindowChur/admindue.h, NewWindowChur/admindue.ui, NewWindowChur/adminhome.ui, NewWindowChur/adminoverdue.cpp, NewWindowChur/adminoverdue.h, NewWindowChur/adminoverdue.ui, NewWindowChur/adminreturned.cpp, NewWindowChur/adminreturned.h, NewWindowChur/adminreturned.ui, NewWindowChur/adminsystem.cpp, NewWindowChur/adminsystem.h, NewWindowChur/adminuser.cpp, NewWindowChur/adminuser.h, NewWindowChur/adminuser.ui
=> Admin stuff

NewWindowChur/catalogue.cpp, NewWindowChur/createfiles.cpp, NewWindowChur/mainwindow.cpp, NewWindowChur/mainwindow.h, NewWindowChur/mainwindow.ui
On Login clicked will now check the members file to see if they exist
=> Login function updated

NewWindowChur/catalogue.ui, NewWindowChur/loginscreen.cpp, NewWindowChur/loginscreen.h, NewWindowChur/mainwindow.cpp, NewWindowChur/mainwindow.h, NewWindowChur/mainwindow.ui, NewWindowChur/signupscreen.cpp, NewWindowChur/signupscreen.h
Connected the logins/sign up screens close and open buttons.
We also talked about: 
- changing the next button on the signup screen to "Sign Up".
- removing the back button on signupscreen2
- changing Sign Up! button to "Log in" on signupscreen 2
=> Connected login/signup screens

NewWindowChur/catalogue.cpp, NewWindowChur/catalogue.h, NewWindowChur/catalogue.ui, NewWindowChur/checkoutscreen.cpp, NewWindowChur/checkoutscreen.h, NewWindowChur/checkoutscreen.ui, NewWindowChur/loginscreen.cpp, NewWindowChur/mainwindow.cpp, NewWindowChur/signupscreen.cpp
Member name and id are now sent to checkoutscreen
=> Connected member details to checkoutscreen

NewWindowChur/NewWindowChur.pro
This reverts commit bc9dbcadd9f8c7137eef15b186df9694486b07cd.
I accidentally deleted the project file, this is what is called "an epic fail".
Change has been reverted
=> Revert "Delete NewWindowChur.pro"

.gitignore, NewWindowChur/catalogue.cpp, NewWindowChur/catalogue.ui, NewWindowChur/createfiles.cpp, NewWindowChur/loginscreen.cpp, NewWindowChur/loginscreen.ui, NewWindowChur/signupscreen.cpp
If a books copies are below 0, we don't append it to the fileData list. This makes sure we don't output a book with 0 copies for a user to check out
=> Copies check in returning catalogue data

NewWindowChur/catalogue.cpp, NewWindowChur/checkoutscreen.cpp, NewWindowChur/checkoutscreen.h, NewWindowChur/createfiles.cpp
Lara made a good point that the user should still be able to pre-book if the books copies are at 0. Therefore, we still need to see it be available on the catalogue!
I changed the CreateFilesOnStartUp functionality so that it checks if EVERY file exists, rather than just the CSVFiles folder
=> Reverted copies check for catalogue and changed CFOSU functionality

NewWindowChur/NewWindowChur.pro.user, NewWindowChur/NewWindowChur.pro.user.34e5ebb, NewWindowChur/admincatalogue.cpp, NewWindowChur/admincatalogue.h, NewWindowChur/admincatalogue.ui, NewWindowChur/admineditbook.cpp, NewWindowChur/admineditbook.h, NewWindowChur/admineditbook.ui, NewWindowChur/catalogue.ui
=> Breaking da library

NewWindowChur/NewWindowChur.pro.user, NewWindowChur/admincatalogue.cpp, NewWindowChur/catalogue.cpp, NewWindowChur/checkoutscreen.cpp, NewWindowChur/createfiles.cpp, NewWindowChur/createfiles.h, NewWindowChur/reservebook.cpp, NewWindowChur/reservebook.h, NewWindowChur/reservebook.ui
Still need to minus 1 from book copies if a book has been checked out and stuff
=> Added reserve book functionality

NewWindowChur/NewWindowChur.pro.user, NewWindowChur/admincatalogue.cpp, NewWindowChur/admineditbook.cpp, NewWindowChur/admineditbook.h, NewWindowChur/admineditbook.ui, NewWindowChur/createfiles.cpp
Added some working functions to the edit button book in admin
=> Edit book admin

NewWindowChur/catalogue.cpp, NewWindowChur/catalogue.h, NewWindowChur/catalogue.ui, NewWindowChur/createfiles.cpp, NewWindowChur/createfiles.h, NewWindowChur/loginscreen.cpp, NewWindowChur/signupscreen.cpp, NewWindowChur/signupscreen.h, NewWindowChur/updateuserdetails.cpp, NewWindowChur/updateuserdetails.h, NewWindowChur/updateuserdetails.ui
user details works now. Kinda.
=> Update user details functionality

NewWindowChur/NewWindowChur.pro.user.ee68ccd, NewWindowChur/admincatalogue.cpp, NewWindowChur/admincatalogue.h, NewWindowChur/admincatalogue.ui, NewWindowChur/admindue.ui, NewWindowChur/admineditbook.cpp, NewWindowChur/admineditbook.h, NewWindowChur/admineditbook.ui, NewWindowChur/adminhome.ui, NewWindowChur/adminoverdue.ui, NewWindowChur/adminreturned.ui, NewWindowChur/adminsystem.ui, NewWindowChur/adminuser.ui, NewWindowChur/catalogue.h, NewWindowChur/createfiles.cpp, NewWindowChur/createfiles.h
=> Able to edit books

NewWindowChur/catalogue.cpp
=> Set up the initial code for users checked out books

NewWindowChur/NewWindowChur.pro, NewWindowChur/NewWindowChur.pro.user, NewWindowChur/SystemFiles.cpp, NewWindowChur/SystemFiles.h, NewWindowChur/catalogue.cpp, NewWindowChur/main.cpp, NewWindowChur/overdue.cpp, NewWindowChur/overdue.h, NewWindowChur/overdue.ui, NewWindowChur/reservebook.cpp, NewWindowChur/reservebook.ui
=> Working on overdue system

NewWindowChur/NewWindowChur.pro.user, NewWindowChur/SystemFiles.cpp, NewWindowChur/overdue.cpp, NewWindowChur/reservebook.cpp, NewWindowChur/updateuserdetails.cpp
If a user has an overdue book(s), the system will display a window with all of their overdue books that need to be returned along with their return date. This is done by checking the users ID as they log in and going through the checkedOutBooks file.
I display a fake message saying a $10 penalty will be applied to their account if they don't return it in time. Nothing actually happens with that.
On startup, the system will now check if a users reserved book has reached it's date for checkout and move it to the checkedOutBooks.csv file.
=> Overdue And ReserveBook functionality.

NewWindowChur/NewWindowChur.pro.user, NewWindowChur/signupscreen.h, NewWindowChur/umlclassdiagrams.qmodel, NewWindowChur/updateuserdetails.h
changed and updated a few comments
=> Yesterdays updates

NewWindowChur/SystemFiles.cpp, NewWindowChur/admindue.cpp, NewWindowChur/admindue.h, NewWindowChur/adminreturned.cpp, NewWindowChur/reservebook.cpp, NewWindowChur/signupscreen.cpp
admindue was having issues with connecting a slot that takes an argument. Now we know, connecting a slot with a parameter is not easy!!@!!!!!
=> Dealt with admindue issue

NewWindowChur/NewWindowChur.pro.user, NewWindowChur/SystemFiles.cpp
=> Logs for Nearby DueDates and Overdue books working

NewWindowChur/NewWindowChur.pro.user, NewWindowChur/catalogue.cpp, NewWindowChur/catalogue.h, NewWindowChur/catalogue.ui, NewWindowChur/main.cpp, NewWindowChur/overdue.cpp, NewWindowChur/reservebook.cpp, NewWindowChur/reservebook.ui, NewWindowChur/signupscreen.cpp, NewWindowChur/signupscreen.h, NewWindowChur/updateuserdetails.cpp
- Increased size of the catalogue window
- Users can no longer sign up with the 'admin' username.
- Signupscreen functionality fixed, you don't need to click on an avatar twice to enable the next button.
- Updated comments on the overdue screen and the reservebook screen.
=> Changes to Jakob's screens + signupscreen

NewWindowChur/NewWindowChur.pro, NewWindowChur/NewWindowChur.pro.user, NewWindowChur/catalogue.cpp, NewWindowChur/checkoutscreen.cpp, NewWindowChur/checkoutscreen.ui, NewWindowChur/mainwindow.cpp, NewWindowChur/reservebook.cpp
- Updated CheckOutScreen UI.
- Updated the QMessageBox's for CheckOutScreen and ReserveBook. Changed their titles and icons to be in line with the rest of the program.
=> Updated checkoutscreen and reservebook

YoobeeLibrarySystem/YoobeeLibrarySystem.pro, YoobeeLibrarySystem/YoobeeLibrarySystem.pro.user, YoobeeLibrarySystem/YoobeeLibrarySystemRC.rc, YoobeeLibrarySystem/version.h
- Updates the projects properties page
- Gives information when mousing over our .exe
=> Added version.h and .rc file
